//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlogApp.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string messageErrorDisconnected {
            get {
                return ResourceManager.GetString("messageErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài ít nhất 8 ký tự, có chứa số và ký tự đặc biệt.
        /// </summary>
        internal static string messageErrorPassword {
            get {
                return ResourceManager.GetString("messageErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài ít nhất 8 ký tự.
        /// </summary>
        internal static string messageErrorUsername {
            get {
                return ResourceManager.GetString("messageErrorUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string textButtonExit {
            get {
                return ResourceManager.GetString("textButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt hình ảnh.
        /// </summary>
        internal static string textButtonImage {
            get {
                return ResourceManager.GetString("textButtonImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        internal static string textButtonInfomation {
            get {
                return ResourceManager.GetString("textButtonInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string textButtonLogout {
            get {
                return ResourceManager.GetString("textButtonLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        internal static string textButtonSetting {
            get {
                return ResourceManager.GetString("textButtonSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string textDisconnect {
            get {
                return ResourceManager.GetString("textDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR.
        /// </summary>
        internal static string textOr {
            get {
                return ResourceManager.GetString("textOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string textRemember {
            get {
                return ResourceManager.GetString("textRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THEME.
        /// </summary>
        internal static string textTheme {
            get {
                return ResourceManager.GetString("textTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string titleButtonLogin {
            get {
                return ResourceManager.GetString("titleButtonLogin", resourceCulture);
            }
        }
    }
}
