//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinEntity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinEntity.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã lớp.
        /// </summary>
        internal static string subTextIdGrade {
            get {
                return ResourceManager.GetString("subTextIdGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã sinh viên.
        /// </summary>
        internal static string subTextIdStudent {
            get {
                return ResourceManager.GetString("subTextIdStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên lớp.
        /// </summary>
        internal static string subTextNameGrade {
            get {
                return ResourceManager.GetString("subTextNameGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên sinh viên.
        /// </summary>
        internal static string subTextNameStudent {
            get {
                return ResourceManager.GetString("subTextNameStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string textBirthdayStudent {
            get {
                return ResourceManager.GetString("textBirthdayStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ảnh.
        /// </summary>
        internal static string textChooseAvatar {
            get {
                return ResourceManager.GetString("textChooseAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string textGenderStudent {
            get {
                return ResourceManager.GetString("textGenderStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã lớp.
        /// </summary>
        internal static string textIdGrade {
            get {
                return ResourceManager.GetString("textIdGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sinh viên.
        /// </summary>
        internal static string textIdStudent {
            get {
                return ResourceManager.GetString("textIdStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên lớp.
        /// </summary>
        internal static string textNameGrade {
            get {
                return ResourceManager.GetString("textNameGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sinh viên.
        /// </summary>
        internal static string textNameStudent {
            get {
                return ResourceManager.GetString("textNameStudent", resourceCulture);
            }
        }
    }
}
